### ISSUE TITLE
Question - Template - Status

### ISSUE THREAD

**Issue by olibos** [tijsverkoyen/HomeAssistant-FusionSolar#50]
Hello @tijsverkoyen ,

Since #22 , my templates shows the status code instead of the readable state.
Do you know how I can "translate" those magic numbers?

```mustache
{{states('sensor.inverter_1_inverter_status')}}
```
get: 512
desired: Grid connection

**Comment by tijsverkoyen** [comment]
Which version of Home Assistant are you using?

**Comment by GiorgioUghini** [comment]
I think this relates with HA and not directly with this integration.
Displaying 512 instead of a string is the wanted behavior as you can interpret 512 as a state that does not change if you change localization.
See this pull request in HA core: https://github.com/home-assistant/core/pull/65743

P.s.: really need to have the localization in your template? As a temporary solution you can use a custom component like this one: https://github.com/PiotrMachowski/Home-Assistant-custom-components-Custom-Templates

**Comment by olibos** [comment]
Hello @tijsverkoyen ,
Here is my setup:
```
Home Assistant 2023.2.0
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230201.0 - latest
```
Here is a sample of my Issue:
![image](https://user-images.githubusercontent.com/6031263/216160929-5f580cfc-6ea6-4118-83f5-e1fd67ac0d7a.png)
With the following YAML
```yaml
  - entity: sensor.inverter_1_active_power
    type: custom:template-entity-row
    secondary: |
      {{states('sensor.inverter_1_inverter_status')}}
    icon: mdi:solar-power
    name: Soleil
```
As @GiorgioUghini says, it's not related to your integration but more a general question.
And I agree in most scenarios it's easier to handle codes than texts but for Lovelace dashboard it's not really user friendly 🤪.

I'll try @GiorgioUghini 's workaround in the meaning time, I'll let you know if it works for me
